### PR TITLE
refactor: angular 16 with signals

### PR DESCRIPTION
**Pull request by faragly**
I know you've been trying to use signals, I think the time has come.

### CODE REVIEW

**Comment by peterpeterparker** [comment]
That's great @faragly 🤟

Indeed I had a try to signal, looks super neat. I even reported one or two bugs which were fixed by the Angular team.

However, for the time being, I think it's still worth to also have a RxJS sample. Therefore, would you mind submitting /modifying your PR to provide the code in another additional sample ("folder")?

What I mean is having in the repo both the RxJS sample and your Signals sample.

e.g.

```
buildwithjuno/examples/angular/diary-rxjs
buildwithjuno/examples/angular/diary-signals
```

or something, open to better idea.

WDYT?

**Comment by faragly** [comment]
I think such a division is meaningless, because the signals are not able to replace rxjs, they are created for different purposes. For asynchronous code, we need rxjs, you can look at DocsService and you will understand what I mean.

**Comment by peterpeterparker** [comment]
I was more thinking that not all Angular developers have already adopted or tried Signals. That's why to easily onboard developers on Juno, I though it is worth to provide those what they feel the most confortable with, RxJS or Signals.

Did not though about the technogology, one or the others, but really more about providing examples that might not confuse developers so that they feel home, you know what I mean?

**Comment by peterpeterparker** [comment]
Thanks a lot for the PR 🔥💪. Really super cool!

Note: I thought about it again, I think for now it's still useful to have both samples. In the future not but, for now, might be handy. So I'll rename it and provide the "old" rxjs sample next to it.

**Comment by faragly** [comment]
Thank you David for letting me be part of this project, you are doing amazing things! I was going to rename the folders and revert back to your original rxjs code, but I got too carried away with vetKD, a demo implementation of which I found in one of the dfinity/examples branches 👀

**Comment by peterpeterparker** [comment]
> with vetKD, a demo implementation of which I found in one of the dfinity/examples branches 👀

That sounds super cool!!!!

Thanks for the kind message and again for the help, really super duper cool!

**Pull request merged**
